questions =  [
    {"id": 0, "question": "Die Freiheit der Unternehmen ist der einzige Weg zu einer florierenden Gesellschaft.", "effects": {"right": 1}},
    {"id": 1, "question": "Wohltätigkeitsvereine sind ein besserer Weg Menschen in Not zu helfen als Sozialhilfen.", "effects": {"right": 1}},
    {"id": 2, "question": "Lohn ist immer fair, da Arbeitgeber am besten wissen, was die Arbeit der Angestellten wert ist.", "effects": {"right": 1}},
    {"id": 3, "question": "Es ist \"die Natur des Menschen\" gierig zu sein. ", "effects": {"right": 1}},
    {"id": 4, "question": "\"Ausbeutung\" ist ein veralteter Begriff, die Probleme des Kapitalismus des 18. Jahrhunderts existieren nichtmehr.", "effects": {"right": 1}},
    {"id": 5, "question": "Kommunismus ist ein Ideal, das umgesetzt nicht funktionieren kann.", "effects": {"right": 1}},
    {"id": 6, "question": "Die Besteuerung der Reichen ist eine schlechte Idee, ohne sie würde es der Gesellschaft besser gehen.", "effects": {"right": 1}},
    {"id": 7, "question": "Umso mehr du dich anstrengst, desto mehr schreistest du die soziale Leiter hinauf.", "effects": {"right": 1}},
    {"id": 8, "question": "Organisations and corporations cannot be trusted and need to be regulated by the government.", "effects": {"right": -1}},
    {"id": 9, "question": "Eine Regierung, die alle versorgt ist von Natur aus eine gute Idee.", "effects": {"right": -1}},
    {"id": 10, "question": "Das momentane Sozialsystem sollte erweitert werden um Ungleichheit stärker zu bekämpfen.", "effects": {"right": -1}},
    {"id": 11, "question": "Land sollte eine Ware sein, die gekauft und gehandelt werden kann.", "effects": {"right": -1}},
    {"id": 12, "question": "Alle Industrien und die Bank sollten verstaatlicht werden.", "effects": {"right": -1}},
    {"id": 13, "question": "Klassenunterschiede sind Hauptgrund für die Trennung der Gesellschaft.", "effects": {"right": -1}},
    {"id": 14, "question": "Es gibt zu viel wirtschaftliche Ungleichheit in der Welt.", "effects": {"right": -1}},
    {"id": 15, "question": "Manchmal ist es richtig für eine Regierung ihre Bürger zu überwachen um Extremismus und Terrorismus zu bekämpfen.", "effects": {"auth": 1}},
    {"id": 16, "question": "Machtfiguren sind gut für die Gesellschaft, solange sie moralisch sind.", "effects": {"auth": 1}},
    {"id": 17, "question": "Stärke ist für eine Regierung nötig um Erfolg zu haben.", "effects": {"auth": 1}},
    {"id": 18, "question": "Nur die Regierung kann Organisationen fair und effektiv regulieren.", "effects": {"auth": 1}},
    {"id": 19, "question": "Die Gesellschaft braucht Struktur und Bürokratie um zu funktionieren.", "effects": {"auth": 1}},
    {"id": 20, "question": "Verpflichtende Ausweise sollten verwendet werden um die allgemeine Sicherheit zu gewährleisten.", "effects": {"auth": 1}},
    {"id": 21, "question": "In Krisenzeitenwird Sicherheit wichtiger als gesellschaftliche Freiheiten.", "effects": {"auth": 1}},
    {"id": 22, "question": "Wenn du nichts zu verstecken hast, musst du nichts fürchten.", "effects": {"auth": 1}},
    {"id": 23, "question": "Die Regierung sollte sich mehr aus dem Alltag der Bürger herraushalten.", "effects": {"auth": -1}},
    {"id": 24, "question": "Ohne Demokratie wäre eine Gesellschaft nichts.", "effects": {"auth": -1}},
    {"id": 25, "question": "Das amerikanische Verfahren der 'Jury Nullification', bei dem die Geschworenen entgegen der Gesetzeslage entscheiden,  sollte legal sein.", "effects": {"auth": -1}},
    {"id": 26, "question": "Je kleiner die Regierung, desto freier das Volk.", "effects": {"auth": -1}},
    {"id": 27, "question": "Die Regierung sollte maximal Notfalldienste und Strafverfolgung zu verfügungstellen.", "effects": {"auth": -1}},
    {"id": 28, "question": "Die Polizei existiert nicht um das Volk zu verteidigen sondern um den Status Quo beizubehalten.", "effects": {"auth": -1}},
    {"id": 29, "question": "Staatliche Schulen sind eine schlechte Idee, da der Staat die Kinder nicht beeinflussen sollte.", "effects": {"auth": -1}},
    {"id": 30, "question": "Zwei einvernehmlich zustimmende Individuen sollten miteinander tun können was sie wollen, selbst wenn es mir unangenehm ist.", "effects": {"prog": 1}},
    {"id": 31, "question": "Der Körper eines Individiuums ist sein Eigentum und es sollte damit machen können was es will.", "effects": {"prog": 1}},
    {"id": 32, "question": "Eine Person sollte verehren können wen oder was sie will.", "effects": {"prog": 1}},
    {"id": 33, "question": "Nacktheit ist komplett normal.", "effects": {"prog": 1}},
    {"id": 34, "question": "Tiere verdienen bestimmte allgemeine Rechte.", "effects": {"prog": 1}},
    {"id": 35, "question": "Geschlecht (gender) ist von der Gesellschaft gegeben und keine natürliche Sachlage.", "effects": {"prog": 1}},
    {"id": 36, "question": "Gesetze die auf kulturellen Werten und nicht auf ethischen basieren sind nicht rechtens.", "effects": {"prog": 1}},
    {"id": 37, "question": "Die körperliche Selbstbestimmung trifft auch auf Minderjährige, psychisch Kranke und schwer Kriminelle zu.", "effects": {"prog": 1}},
    {"id": 38, "question": "Homosexualität ist gegen meine Werte.", "effects": {"prog": -1}},
    {"id": 39, "question": "Transgender Individuen sollten keine Kinder adoptieren können.", "effects": {"prog": -1}},
    {"id": 40, "question": "Drogen sind schädlich und sollten verboten werden.", "effects": {"prog": -1}},
    {"id": 41, "question": "Die Todenstrafe sollte für manche Verbrechen möglich sein.", "effects": {"prog": -1}},
    {"id": 42, "question": "Verbrechen ohne Opfer sollten trotzdem bestraft werden.", "effects": {"prog": -1}},
    {"id": 43, "question": "Niemand kann ohne Religion moralisch sein.", "effects": {"prog": -1}},
    {"id": 44, "question": "Eltern sollten absolute Macht über ihre Kinder haben, da sie älter sind und mehr Erfahrung haben.", "effects": {"prog": -1}},
    {"id": 45, "question": "Multikulturalismus ist schlecht.", "effects": {"prog": -1}}
];
